### ISSUE TITLE
Should this plugin use fast-jwt?

### ISSUE THREAD

**Issue by jkirkpatrick24** [fastify/fastify-jwt#174]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hello there! I was wondering if this plugin would benefit from replacing the [jsonwebtoken](https://github.com/auth0/node-jsonwebtoken) package with fast-jwt.

Based this article: https://www.nearform.com/blog/improve-json-web-tokens-performance-in-node-js/, it looks like fast-jwt would give a performance bump to applications using this plugin.

Is there any reason why this shouldn't be changed?

Thanks!

**Comment by mcollina** [comment]
I think we should change it. We didn't at the beginning because we wanted to validate fast-jwt in the wild for a bit.

Would you like to send a PR?

**Comment by jkirkpatrick24** [comment]
Sure, I'd be happy to 👍

**Comment by climba03003** [comment]
I have missed this issue. 

I can see that in the last part of article, it stated that `fast-jwt` is an experimental library and the repository is not very active. I have check with the benchmark in [here](https://github.com/nearform/fast-jwt#benchmarks). `jose` is the second fastest compare between `fast-jwt`, `jsonwebtoken` and `jose`.

The community of `jose` is more active and it support more format and platform (cjs, esm, cloudflare, etc) than `jsonwebtoken` does. Instead of `fast-jwt`, should we consider `jose` first? @mcollina wdyt?

**Comment by mcollina** [comment]
I would not call https://github.com/nearform/fast-jwt experimental anymore.

I kind of not see the point of moving to jose as things would already work well here.

**Comment by climba03003** [comment]
I am welcome on changing package that is better and stable for production use.
As you claim that it is not experimental anymore. I am totally fine with it.

**Comment by mcollina** [comment]
FWIW we have used in a few sensitive projects and it all went fine, so I would use it from my point of view.
