### ISSUE TITLE
reply.jwtSign without callback and with expiresIn sets wrong exp in payload

### ISSUE THREAD

**Issue by maticjeras** [fastify/fastify-jwt#207]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.25.1

### Plugin version

4.1.1

### Node.js version

16.13

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.1

### Description

Creating a token using reply.jwtSign when expires option is set (either when registering fastify-jwt or in the method) puts an exp field in the token payload that is 1000x too far in the future. This only happens when no callback is passed.

I think the problem is that replySign function calls itself again with a callback. Then convertTemporalProps gets called on the options again multiplying fields that are already converted to ms by 1000. 
https://github.com/fastify/fastify-jwt/blob/767c64d881994e9735147f546219a1d534134f7e/jwt.js#L311-L331

A possible solution would be to assign next (callback) in the Promise constructor and return the resulting promise at the end of the function. 
EDIT: This breaks when secret is a function. Moving next === undefined block above if (options.sign) seems to not break anything :)

### Steps to Reproduce

1. set sign.expiresIn when registering fastify-jwt or directly in reply.jwtSign options
2. create a token using reply.jwtSign
3. compare payload.exp - payload.iat to expiresIn

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by maticjeras** [comment]
Thank you for the quick reply. I'll send a pull request.

**Comment by Unelith** [comment]
This is still occasionally problematic. For example, when using the following options in `fastify.register`:
```typescript
sign: {
	algorithm: 'HS512',
	expiresIn: '24h',
}
```

Pulling those options out later through `fastify.jwt.options.sign` sees the time converted to milliseconds as a number:
```typescript
sign: {
	algorithm: 'HS512',
	expiresIn: 86400000,
}
```

So if I want to locally merge the global sign options with some extra ones on top of that, not unlike the example provided in the documentation, such as:
```typescript
const signOptions = Object.assign({}, fastify.jwt.options.sign, { jti });
const token = fastify.jwt.sign({ userId: req.user.id }, signOptions);
```

The `expiresIn` value that gets passed to `fastify.jwt.sign` in here is in milliseconds and a number, while numbers are assumed to be **seconds** by default. As a result, the actual value used is 1000 times as big. This makes it so that I have to store and pass around my global fastify-jwt options separately. Moreover, one must make sure to store a clone of the options, because they seem to be modified in place.
