### ISSUE TITLE
Fastify instance is not decorated

### ISSUE THREAD

**Issue by samevision** [fastify/fastify-jwt#77]
Hello guys,

I tried to implement JWT into my code but I can't access the methods, because fastify.jwt is undefined. If I try to user fastify.jwt.sign() I receive an error: Cannot read property 'sign' of undefined.

```
const fastify = require('fastify')()
fastify.register(require('fastify-jwt'), {
    secret: 'SECRETSECRETSECRETSECRETSECRETSECRETSECRET'
})
async (req, res, next) => {
    const token = await fastify.JWT.sign({ user: 1 })
    await res.send(token);
}
```

I appreciate your help.
Best

**Comment by Eomm** [comment]
Could add a complete example to reproduce?

Moreover you should not use `next` with `async function`: you can remove it

**Comment by samevision** [comment]
Thanks for the hint.

I believe the problem could be that I export this function.

**app.js**
```
const fastify = require('fastify')({ logger: true })
fastify.register(require('fastify-jwt'), {
  secret: 'supersecretsupersecretsupersecretsupersecret'
})
fastify.register(require('./routes/index'), { prefix: '' })
```

**route.js**
```
module.exports = function (router, opts, done) {
let dev = require('../controllers/dev')
router.get('/test', dev.test)
done()
}
```

**controller.js**
const fastify = require('fastify')()
exports.test = async (req, res, next) => {
    const token = fastify.jwt.sign({ user: 1 })
    res.send(token)
}

**Comment by Eomm** [comment]
The decorated fastify instance has been created in `app.js` so, if you run `const fastify = require('fastify')()` in `controller.js` you are creating a brand new instance without the JWT.

You need to create only one fastify instace and use always that one.

So I would suggest changing the controller to:

```
exports.test = function (req, res) {
    const token = this.jwt.sign({ user: 1 })
    res.send(token)
}
```

Because if you use a simple `function` as a handler (not an arrow function), the `this` will be binded to the root fastify instance.

Moreover you need to know that here `module.exports = function (router, opts, done) {` the "router" parameter **is** the fastify instance, so you can pass it to the `dev.test` for example.

**Comment by samevision** [comment]
Really helpful. Got it!

I added `module.exports = fastify` to my app.js an was able to call it with `const fastify = require('../app')`. ☺️

**Comment by Eomm** [comment]
Your welcome
